### ISSUE TITLE
channel.create接口没有权限, hubot已经在所有人里

### ISSUE THREAD

**Issue by unix2dos** [bearyinnovative/OpenAPI#26]

**Comment by shonenada** [comment]
Hello @unix2dos ，这边验证 hubot 可以正常创建讨论组。
麻烦提供一下 Hubot Token 以及调用的参数（或代码）（为了信息安全，请发送邮件到 shonenada at beary.chat) ，我们将进一步定位问题。

**Comment by unix2dos** [comment]
> Hello @unix2dos ，这边验证 hubot 可以正常创建讨论组。
> 麻烦提供一下 Hubot Token 以及调用的参数（或代码）（为了信息安全，请发送邮件到 shonenada at beary.chat) ，我们将进一步定位问题。

刚试了可以的.之前我在管理面板把创建公开讨论组的权限改成仅管理员了.......
